// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function ClearLogs() {
    return $Call.ByID(2790474131);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableVersions(name) {
    return $Call.ByID(112013489, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLogs() {
    return $Call.ByID(3928212514);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.ToolInfo | null>}
 */
export function GetToolInfo(name) {
    return $Call.ByID(2326650287, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(984509731);
}

/**
 * @param {string} name
 * @param {string} version
 * @returns {$CancellablePromise<string>}
 */
export function InstallTool(name, version) {
    return $Call.ByID(1767063536, name, version);
}

/**
 * @returns {$CancellablePromise<$models.ToolInfo[]>}
 */
export function ListInstalledTools() {
    return $Call.ByID(3487203710).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function MiseDoctor() {
    return $Call.ByID(400114682);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Reshim() {
    return $Call.ByID(2532334235);
}

/**
 * @param {string} args
 * @returns {$CancellablePromise<string>}
 */
export function RunCustomCommand(args) {
    return $Call.ByID(513464192, args);
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<$models.RegistryTool[]>}
 */
export function SearchRegistry(query) {
    return $Call.ByID(1580658152, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} name
 * @param {string} version
 * @returns {$CancellablePromise<string>}
 */
export function SetDefaultVersion(name, version) {
    return $Call.ByID(3380973186, name, version);
}

/**
 * @param {string} name
 * @param {string} version
 * @returns {$CancellablePromise<string>}
 */
export function UninstallTool(name, version) {
    return $Call.ByID(2366169021, name, version);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.ToolInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType1);
const $$createType4 = $models.RegistryTool.createFrom;
const $$createType5 = $Create.Array($$createType4);
