// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RegistryTool {
    /**
     * Creates a new RegistryTool instance.
     * @param {Partial<RegistryTool>} [$$source = {}] - The source object to create the RegistryTool.
     */
    constructor($$source = {}) {
        if (!("short" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["short"] = "";
        }
        if (!("backends" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["backends"] = [];
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("aliases" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["aliases"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistryTool instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RegistryTool}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backends" in $$parsedSource) {
            $$parsedSource["backends"] = $$createField1_0($$parsedSource["backends"]);
        }
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField3_0($$parsedSource["aliases"]);
        }
        return new RegistryTool(/** @type {Partial<RegistryTool>} */($$parsedSource));
    }
}

export class ToolInfo {
    /**
     * Creates a new ToolInfo instance.
     * @param {Partial<ToolInfo>} [$$source = {}] - The source object to create the ToolInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("versions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["versions"] = [];
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField2_0($$parsedSource["versions"]);
        }
        return new ToolInfo(/** @type {Partial<ToolInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
